### ISSUE TITLE
关于子进程识别是否处于平滑重启的思路

### ISSUE THREAD

**Issue by buexplain** [fevin/gracehttp#3]
[https://github.com/tabalt/gracehttp/blob/master/server.go](url)
老哥你可以参考一下上面这位老哥的代码，他采用的是环境变量来识别的。

**Comment by fevin** [comment]
嗯，赞，用环境变量做标志这个想法挺好～

**Comment by fevin** [comment]
已经采用环境变量的方式来识别是否为重启~👍
